# **Hand Written Digit Prediction - Classifiication Analysis**
# Attributes Information

The didgit dataset consists of 8x8 pixel images of digits .the images attribute of the dataset stores 8x8 arrays of grayscale values for each image. We will use these arrays to visualize the first 4 images . The target attribute of the dataset stores the digit each image represents.

# **Import Library**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# **Import Data**

In [ ]:
from sklearn.datasets import load_digits

In [ ]:
df = load_digits()

# **Data Preproccessing**
Flatten Image

In [ ]:
df.images.shape

(1797, 8, 8)

In [ ]:
df.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [ ]:
df.images[0].shape

(8, 8)

In [ ]:
n_samples = len(df.images)
data = df.images.reshape(n_samples,-1)

In [ ]:
data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [ ]:
data[0].shape

(64,)

In [ ]:
data.shape

(1797, 64)

# **Scaling the Data**

In [ ]:
data.min()

0.0

In [ ]:
data.max()

16.0

In [ ]:
data=data/16

In [ ]:
data.min()

0.0

In [ ]:
data.max()

1.0

In [ ]:
data[0]

array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])

# **Train Test Split Data**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train , X_test, y_train , y_test =train_test_split(data ,df.target , train_size=0.7,random_state=182529)

In [ ]:
X_train.shape , X_test.shape, y_train.shape , y_test.shape

((1257, 64), (540, 64), (1257,), (540,))

# **Random Forest Model**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf= RandomForestClassifier()

In [ ]:
rf.fit(X_train,y_train)

RandomForestClassifier()

# **Predict Test Data**

In [ ]:
y_pred=rf.predict(X_test)

In [ ]:
y_pred

array([4, 6, 4, 9, 8, 1, 0, 3, 7, 7, 0, 2, 1, 5, 6, 7, 5, 5, 6, 9, 8, 4,
       4, 1, 9, 8, 8, 8, 5, 0, 6, 7, 1, 5, 3, 4, 7, 0, 4, 6, 7, 1, 2, 8,
       1, 2, 9, 0, 2, 8, 5, 0, 5, 8, 8, 5, 4, 3, 3, 0, 1, 9, 5, 9, 2, 5,
       6, 5, 9, 8, 1, 3, 2, 1, 6, 0, 3, 6, 9, 0, 3, 3, 1, 3, 7, 4, 0, 9,
       3, 8, 2, 2, 2, 8, 7, 8, 9, 7, 2, 1, 7, 9, 3, 3, 4, 7, 7, 4, 9, 5,
       3, 9, 1, 4, 2, 2, 6, 7, 8, 6, 3, 1, 3, 5, 1, 5, 7, 7, 1, 9, 7, 2,
       7, 6, 0, 0, 4, 3, 8, 8, 1, 8, 9, 4, 6, 7, 6, 4, 9, 5, 2, 7, 1, 5,
       8, 0, 3, 6, 6, 5, 0, 9, 1, 4, 4, 6, 3, 7, 0, 3, 8, 8, 3, 7, 2, 4,
       2, 0, 9, 6, 2, 7, 4, 0, 7, 3, 5, 2, 3, 1, 3, 5, 3, 1, 5, 0, 5, 8,
       1, 6, 6, 5, 9, 4, 6, 8, 9, 0, 6, 9, 1, 9, 3, 5, 2, 5, 3, 8, 9, 5,
       4, 6, 7, 9, 8, 4, 3, 3, 4, 0, 8, 0, 2, 0, 1, 7, 4, 2, 9, 5, 4, 7,
       5, 8, 5, 3, 1, 7, 7, 5, 6, 3, 7, 3, 8, 4, 4, 7, 0, 1, 9, 8, 3, 1,
       3, 6, 5, 7, 1, 5, 4, 8, 0, 6, 2, 4, 3, 0, 5, 7, 4, 3, 1, 3, 0, 3,
       1, 0, 1, 4, 6, 8, 3, 6, 3, 8, 7, 6, 7, 5, 3,

# **Model Accuracy**

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
confusion_matrix(y_test, y_pred)

array([[53,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 50,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 50,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 63,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 48,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0, 48,  1,  0,  1,  2],
       [ 0,  1,  0,  0,  0,  0, 56,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 58,  0,  0],
       [ 0,  1,  1,  0,  1,  1,  0,  1, 48,  0],
       [ 0,  0,  0,  0,  1,  1,  0,  0,  0, 51]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        54
           1       0.96      1.00      0.98        50
           2       0.98      1.00      0.99        50
           3       1.00      0.98      0.99        64
           4       0.94      0.98      0.96        49
           5       0.96      0.92      0.94        52
           6       0.98      0.98      0.98        57
           7       0.98      1.00      0.99        58
           8       0.96      0.91      0.93        53
           9       0.94      0.96      0.95        53

    accuracy                           0.97       540
   macro avg       0.97      0.97      0.97       540
weighted avg       0.97      0.97      0.97       540

