<a href="https://colab.research.google.com/github/rishabhbiswal007/Hands-on-project-YBI/blob/main/WOMEN_CLOTHS_REVIEW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **WOMEN CLOTHS REVIEW**

# **Import Dependencies**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Load Data**

In [9]:
data = pd.read_csv('/content/Womens Clothing E-Commerce Reviews.csv', index_col = 0)

In [10]:
data.rename(columns = {
    'Review Text': 'Review',
    'Recommended IND': 'Recommended',
    'Positive Feedback Count': 'Positive Feedback',
    'Division Name': 'Division',
    'Department Name': 'Department',
    'Class Name': 'Category'},
            inplace = True)

In [11]:
data.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 2.0+ MB


In [13]:
data.shape

(23486, 10)

# **Missing Values**

In [14]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [15]:
data[data['Review'] == ''] = np.NaN

In [16]:
data['Review'].fillna('No Review', inplace = True)

In [17]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [18]:
data['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

# **Define Target(y) and Feature(X)**

In [19]:
data.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [20]:
X = data['Review']

In [21]:
y = data['Rating']

In [22]:
data['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

# **Train Test Split**

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y, random_state = 182529)

In [25]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Feature text coversion to tokens**

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
cv = CountVectorizer(
                lowercase = True,
                analyzer = 'word',
                ngram_range = (2, 3),
                stop_words = 'english',
                max_features = 5000
                    )

In [29]:
X_train = cv.fit_transform(X_train)

In [30]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 bought', ..., 'years old', 'yoga pants',
       'zipper little'], dtype=object)

In [31]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [32]:
X_test = cv.fit_transform(X_test)

In [33]:
cv.get_feature_names_out()

array(['00p 0p', '10 12', '10 12 12', ..., 'years come', 'yellow color',
       'yoga pants'], dtype=object)

In [34]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# **Train Model**

In [35]:
from sklearn.naive_bayes import MultinomialNB

In [36]:
model = MultinomialNB()

In [37]:
model.fit(X_train, y_train)

MultinomialNB()

# **Model Prediction**

In [38]:
y_pred = model.predict(X_test)

In [39]:
y_pred.shape

(7046,)

In [40]:
y_pred

array([1., 3., 4., ..., 4., 4., 5.])

# **Get Probability of Each Predicted Class**

In [41]:
model.predict_proba(X_test)

array([[7.54663536e-01, 1.22516627e-01, 6.06245440e-03, 4.59597491e-02,
        7.07976341e-02],
       [8.63615757e-02, 3.11739827e-02, 8.46664745e-01, 7.85035013e-03,
        2.79493467e-02],
       [4.76902061e-02, 1.03733181e-01, 1.53312070e-01, 4.37482907e-01,
        2.57781636e-01],
       ...,
       [7.91350737e-02, 8.12670524e-02, 1.82152184e-01, 3.49452031e-01,
        3.07993659e-01],
       [2.51020167e-01, 2.04085383e-02, 9.93376366e-02, 6.28467976e-01,
        7.65681755e-04],
       [1.99868593e-04, 5.55543615e-03, 1.12203920e-02, 5.99244853e-02,
        9.23099818e-01]])

# **Model Evaluation**

In [42]:
from sklearn.metrics import confusion_matrix, classification_report

In [43]:
print(confusion_matrix(y_test, y_pred))

[[  34   32   32   33  122]
 [  68   65   86   79  172]
 [ 127  108  165  154  307]
 [ 205  133  186  305  694]
 [ 421  250  347  635 2286]]


In [44]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.04      0.13      0.06       253
         2.0       0.11      0.14      0.12       470
         3.0       0.20      0.19      0.20       861
         4.0       0.25      0.20      0.22      1523
         5.0       0.64      0.58      0.61      3939

    accuracy                           0.41      7046
   macro avg       0.25      0.25      0.24      7046
weighted avg       0.45      0.41      0.42      7046



# **Recategorize Rating as Poor(0) and Good(1)**

In [45]:
data_recategorized = data.replace({'Rating': {1:0, 2:0, 3:0, 4:1, 5:1}})

In [46]:
y = data_recategorized['Rating']

In [47]:
X = data_recategorized['Review']

# **Train Test Split**

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y, random_state = 18529)

In [50]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Feature text coversion to tokens**

In [51]:
from sklearn.feature_extraction.text import CountVectorizer

In [52]:
cv = CountVectorizer(
                lowercase = True,
                analyzer = 'word',
                ngram_range = (2, 3),
                stop_words = 'english',
                max_features = 5000
                    )

In [53]:
X_train = cv.fit_transform(X_train)

In [54]:
X_test = cv.fit_transform(X_test)

# **Re-Train Model**

In [55]:
from sklearn.naive_bayes import MultinomialNB

In [56]:
model = MultinomialNB()

In [57]:
model.fit(X_train, y_train)

MultinomialNB()

# **Model Prediction**

In [58]:
y_pred = model.predict(X_test)

In [59]:
y_pred.shape

(7046,)

In [60]:
y_pred

array([0., 1., 1., ..., 1., 1., 0.])

# **Model Evaluation**

In [61]:
from sklearn.metrics import confusion_matrix, classification_report

In [62]:
print(confusion_matrix(y_test, y_pred))

[[ 428 1155]
 [1110 4353]]


In [63]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.28      0.27      0.27      1583
         1.0       0.79      0.80      0.79      5463

    accuracy                           0.68      7046
   macro avg       0.53      0.53      0.53      7046
weighted avg       0.68      0.68      0.68      7046

